version: '3.1'
services:
  php:
    container_name: apache-php56
    image: apache-php56:latest
    build:
      dockerfile: Dockerfile.php56
      context: .
    depends_on:
      - 'db'
    ports:
      - '3050:80'
    volumes:
      - ./DatasetTracker:/var/www/html
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
  db:
    image: mysql:5.6.29
    container_name: mysql56
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
    volumes:
      - ./sql-dump:/docker-entrypoint-initdb.d