version: '3.1'
services:
  php:
    container_name: apache-php74-dev
    image: apache-php74-dev
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "$APP_PORT:80"
    volumes:
      - ./src:/var/www/html
    env_file:
      - .env

  phpmyadmin:
    container_name: phpmyadmin-dev
    image: phpmyadmin:latest
    ports:
      - "$PHPMYADMIN_PORT:80"
    env_file:
      - .env