version: '3.1'
services:
  php:
    container_name: apache-php74-prod
    image: apache-php74-prod
    restart: always
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "$APP_PORT:80"
    env_file:
      - .env
    volumes:
      - ./ssl-config/rds-combined-ca-bundle.pem:/etc/ssl/rds-combined-ca-bundle.pem

  phpmyadmin:
    container_name: phpmyadmin-prod
    image: phpmyadmin:latest
    restart: always
    ports:
        - "$PHPMYADMIN_PORT:80"
    volumes:
      - ./ssl-config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./ssl-config/rds-combined-ca-bundle.pem:/etc/phpmyadmin/rds-combined-ca-bundle.pem
    env_file:
      - .env

