version: '3.1'
services:
  php:
    container_name: apache-php74
    image: apache-php74-prod
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - "$APP_PORT:80"
    environment:
        - MYSQL_HOST
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_DATABASE

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
        - "$PHPMYADMIN_PORT:80"
    environment:
        - PMA_HOST

